---
abstract: 'A Tiny API client for MetaCPAN'
author:
  - 'Nicholas R. Perez <nperez@cpan.org>'
build_requires:
  Exporter: 5.57
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaCPAN-API-Tiny
requires:
  Carp: 0
  HTTP::Tiny: 0.017
  JSON::PP: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/nperez/metacpan-api-tiny
version: 1.131730
